= redis-rdb-verify

Verify Redis RDB checksums without Redis.

Supports RDB version 9 (Redis 5).  Verifiable RDBs must be generated by a Redis configured with `rdbchecksum yes`.  (This option is enabled by default.)


== Usage

----
redis-rdb-verify [rdb-path]
----

`rdb-path` is the filesystem path to a https://redis.io/topics/persistence[Redis RDB snapshot].  Any positional arguments after the first are silently ignored.  The RDB is read from standard input if no arguments are supplied.

One line of text is written to standard output after a checksum is computed:

----
% redis-rdb-verify dump.rdb
e1a1218c5228182b        e1a1218c5228182b        ok      dump.rdb

#   computed               recorded           result      path
#   checksum               checksum                   (- if stdin)
----

The computed checksum, represented in the first column of output, is independently calculated by this program.  The recorded checksum, represented in the second column, is read verbatim from the RDB.  The RDB is verified if the checksums concur.  Columns are tab separated.

`redis-rdb-verify` exits with status zero if the RDB was successfully read and if the checksums concur.  A checksum mismatch will elicit status 10; a missing recorded checksum will elicit status 11.

----
% xxd <dump.rdb >dump.rdb.txt

% ed dump.rdb.txt
945601
10p
00000090: 6673 6574 0b33 3039 3133 3032 3137 3931  fset.30913021791
c
00000090: dead beef 0b33 3039 3133 3032 3137 3931
.
wq
945583

% xxd -r <dump.rdb.txt >corrupt.rdb

% redis-rdb-verify corrupt.rdb
98083a7b429682ce        e1a1218c5228182b        checksum mismatch       corrupt.rdb

% echo $?
10
----
